### ISSUE TITLE
Updating Home Page Content

### ISSUE THREAD

**Issue by kburakozdemir** [drupal-tome/drupal-tome.github.io#18]
hi, @mortenson I tried once more with a clean beginning. I'd like to let you know the situation when I update the home page step by step. What is your suggestion about the solution? thanks.

Steps:

1. Fork the repo
2. Clone the fork to local
3. Create new branch from dev
4. Checkout new branch
5. Run `composer install`
6. Run `drush tome:install -y`
7. Run `drush cr`
8. Run `drush runserver`
9. Navigate to home page
10. Run `drush uli --ud 1`
11. Navigate to password reset page
12. Navigate to http://127.0.0.1:8888/node/24/edit?destination=/admin/content
13. Update Paragraphs Hero Text from "A static site generator for Drupal 8" to "A static site generator for Drupal 9"

Workspace was clean until this moment. Screenshot:

![image](https://user-images.githubusercontent.com/1656836/165505314-3ef0387f-9f79-435d-8f77-0fe72637f4bf.png)

14. Press save 
15. After saving home page, I see "The website encountered an unexpected error. Please try again later." and uncomitted changes appear (13 modified files).

![image](https://user-images.githubusercontent.com/1656836/165505364-50ed75f1-5ab0-4b56-9483-571586384ba6.png)

![image](https://user-images.githubusercontent.com/1656836/165505572-76b41f94-fb96-45d0-92f8-be230636c8dc.png)

16. To get read of the "The website encountered an unexpected error. Please try again later." error, I run `drush cr`
17. I refresh the page and see the message "Landing page [Home] has been updated.

![image](https://user-images.githubusercontent.com/1656836/165505901-aed59e9b-af4a-4ddd-afc8-855b12636bde.png)

18. Navigate to home page again
19. The content has changed and there are still 13 modified files:
 
![image](https://user-images.githubusercontent.com/1656836/165506315-506693bb-9efc-4d59-91b0-b4d505d7b748.png)

**Comment by mortenson** [comment]
Thanks @kburakozdemir - let me try to replicate "from scratch" and figure this out...

**Comment by kburakozdemir** [comment]
Thanks. Please wait for my brand new PR!
