### ISSUE TITLE
Drush command terminated abnormally running Tome static

### ISSUE THREAD

**Issue by mcasey8540** [drupal-tome/drupal-tome.github.io#7]
Hi @mortenson 👋, while running Tome static I'm hitting this error. Do you have any recommendations on how to debug?

``` [30;43;1m[warning][39;49;22m Drush command terminated abnormally. Check for an exit() in your Drupal site.```

**command run**

```drush tome:static --uri=www.example.com --yes --path-count=1 --process-count=30 -v --path-pattern='/^(\/(?!es\/|es$|sites\/default\/files|media\/|user\/|feed|admin\/|http|contextual\/|.*autocomplete$)).*$/'```

**Comment by mortenson** [comment]
Hi @mcasey8540 - could you report this bug in the Tome issue queue at https://www.drupal.org/project/issues/tome ? Thanks!
