### ISSUE TITLE
'composer' - install problems

### ISSUE THREAD

**Issue by jordila** [drupal-tome/drupal-tome.github.io#9]
Sadly, i cannot make it work in 2021... due to composer version incompatibilities:

![composer2-error](https://user-images.githubusercontent.com/1966068/109810486-dee53a00-7c29-11eb-8ec3-094e3ccf163d.png)

may i downgrade to Composer v1...i guess ?

**Comment by lucas-c9** [comment]
If you are in linux, you can try as root:
`sudo composer self-update --1`
Hope you can fix it.

**Comment by jordila** [comment]
YEs , it worked @lucas-c9 .ThX

```
Use composer self-update --rollback to return to version 2.0.11
```
